// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v{{.Version}}
// Please do not change anything in this file.
package {{.Package}}
{{if .Imports}}
import ({{range .Imports}}
    {{.}}{{end}}
)
{{end}}
type {{.Name}} struct { {{if .EmbeddingBase}}
    model.Base{{end}}
{{range .Fields}}
    {{.Name}} {{.Type}} `{{.Tag}}`{{end}}
}
{{if .CustomTableName}}
func (*{{.Name}}) TableName() string {
    return "{{.TableName}}"
}{{end}}{{range .Dropdowns}}{{if .DropdownStrings}}
func (*{{.Model.Name}}) {{.Name}}Strings() []string {
    return {{.OptionStrings}}
}{{end}}{{if .DropdownInts}}
func (*{{.Model.Name}}) {{.Name}}Ints() []int {
    return {{.OptionInts}}
}{{end}}{{if .DropdownUints}}
func (*{{.Model.Name}}) {{.Name}}Uints() []uint {
    return {{.OptionUints}}
}{{end}}{{if .DropdownFloats}}
func (*{{.Model.Name}}) {{.Name}}Floats() []float64 {
    return {{.OptionFloats}}
}{{end}}{{if .DropdownDynamicStrings}}
// Please implements this method in another file
// func (*{{.Model.Name}}) {{.Name}}DynamicStrings() []string {
//     return []string{"some", "custom", "strings"}
// }{{end}}{{end}}
{{if .Purge}}
func (*{{.Name}}) Purge() {}
{{end}}{{if .Lazy}}
func (*{{.Name}}) Lazy() {}
{{end}}{{if .Ctrl}}
func (*{{.Name}}) Ctrl() {}
{{end}}