// auto generated by GoalGenerator@v0.1.0
package {{.Package}}
{{if .Imports}}
import ({{range .Imports}}
    {{.}}{{end}}
)
{{end}}
type {{.Name}} struct { {{range .Fields}}
    {{.Name}} {{.Type}}{{end}}
}
